#config.yaml
hyperparameters:
  batch_size: 64
  dataset_path: '~/datasets'
  x_dim: 784
  hidden_dim: 400
  latent_dim: 20
  lr: 0.001
  epochs: 20
  seed: 1234
  reduction_type: 'sum'
  cuda: False
